name: Build and Release Executable

on:
  push:
    branches: [ "main", "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build Executable with PyInstaller
      env:
        PYTHONIOENCODING: "utf-8"
      run: |
        python build_exe.py

    - name: Compress Build Output into Zip
      run: |
        powershell Compress-Archive -Path dist/WhisperSubtitleGenerator -DestinationPath WhisperSubtitleGenerator-Windows.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WhisperSubtitleGenerator-Windows
        path: WhisperSubtitleGenerator-Windows.zip

    - name: Release Executable on GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: WhisperSubtitleGenerator-Windows.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
